***-------------------------------------------------------------------------***;
*** Macro Name:    build_cdisc.sas                                          ***;
***                                                                         ***;
*** Purpose:       Build final SDTM or ADaM datasets from a programmed      ***;
***                intermediate dataset using synchronized SPEC metadata.   ***;
***-------------------------------------------------------------------------***;
*** Programmed By: Manivannan Mathialagan                                   ***;
*** Created On:    04Oct2026                                                ***;
***-------------------------------------------------------------------------***;
*** Input:         Programmed intermediate SAS dataset                      ***;
***                SPEC.SDTM_DATASETS / SPEC.SDTM_VARIABLES                 ***;
***                SPEC.SDTM_SUPPVARIABLES                                  ***;
***                SPEC.ADAM_DATASETS / SPEC.ADAM_VARIABLES                 ***;
***                                                                         ***;
*** Output:        Final dataset in SDTM or ADAM library                    ***;
***                SUPPxx dataset for SDTM when applicable                  ***;
***-------------------------------------------------------------------------***;
*** Parameters:                                                             ***;
*** DEV            SDTM or ADAM                                             ***;
*** INDS           Programmed intermediate dataset                          ***;
*** DSN            Final CDISC dataset name                                 ***;
*** DEBUG          Y keeps temporary BUILD_CDISC datasets defult=N          ***;
***-------------------------------------------------------------------------***;
*** Notes:                                                                  ***;
***                SPEC metadata must be synchronized before execution.     ***;
***                SDTM supplemental source variables use an underscore     ***;
***                prefix in the programmed dataset.                        ***;
***                SDTM --SEQ is generated by STUDYID/USUBJID when present. ***;
***-------------------------------------------------------------------------***;
*** Change History:                                                         ***;
*** Version   Date         Description                                      ***;
*** -------   -----------  -------------------------------------------------***;
*** 1.0       04Oct2026    Initial version.                                 ***;
***-------------------------------------------------------------------------***;

%macro build_cdisc(dev=, inds=, dsn=, debug=N);

    %local _dev _dsn _debug _outlib _dsmeta _varmeta _suppmeta _keep _sort _sort_no_seq _seqvar _seqcnt
           _suppcnt _suppobs _nvars _seqby _dsid _rc _attr _missing _i _var _has_eval _has_idvar;

    %let _dev=%upcase(%sysfunc(strip(%superq(dev))));
    %let _dsn=%upcase(%sysfunc(strip(%superq(dsn))));
    %let _debug=%upcase(%sysfunc(strip(%superq(debug))));

    /* Validate required parameters */
    %if %superq(_dev)= %then %do;
        %put ERROR: BUILD_CDISC: DEV is required.;
        %return;
    %end;

    %if %superq(inds)= %then %do;
        %put ERROR: BUILD_CDISC: INDS is required.;
        %return;
    %end;

    %if %superq(_dsn)= %then %do;
        %put ERROR: BUILD_CDISC: DSN is required.;
        %return;
    %end;

    %if &_dev ne SDTM and &_dev ne ADAM %then %do;
        %put ERROR: BUILD_CDISC: DEV must be SDTM or ADAM. Received DEV=&_dev..;
        %return;
    %end;

    %if &_debug ne Y and &_debug ne N %then %do;
        %put ERROR: BUILD_CDISC: DEBUG must be Y or N. Received DEBUG=&_debug..;
        %return;
    %end;

    %if not %sysfunc(exist(&inds)) %then %do;
        %put ERROR: BUILD_CDISC: Input dataset &inds does not exist.;
        %return;
    %end;

    /* Resolve synchronized metadata and output library */
    %if &_dev=SDTM %then %do;
        %let _outlib=SDTM;
        %let _dsmeta=SPEC.SDTM_DATASETS;
        %let _varmeta=SPEC.SDTM_VARIABLES;
        %let _suppmeta=SPEC.SDTM_SUPPVARIABLES;
    %end;
    %else %do;
        %let _outlib=ADAM;
        %let _dsmeta=SPEC.ADAM_DATASETS;
        %let _varmeta=SPEC.ADAM_VARIABLES;
        %let _suppmeta=;
    %end;

    /* Validate synchronized metadata */
    %if not %sysfunc(exist(&_dsmeta)) %then %do;
        %put ERROR: BUILD_CDISC: Dataset metadata &_dsmeta does not exist.;
        %return;
    %end;

    %if not %sysfunc(exist(&_varmeta)) %then %do;
        %put ERROR: BUILD_CDISC: Variable metadata &_varmeta does not exist.;
        %return;
    %end;

    /* Get final sort order from dataset metadata */
    %let _sort=;

    proc sql noprint;
        select strip(KEY_VARIABLES) into :_sort trimmed
        from &_dsmeta
        where upcase(strip(DATASET))="&_dsn";
    quit;

    %let _sort=%sysfunc(tranwrd(%superq(_sort),%str(,),%str( )));
    %let _sort=%sysfunc(compbl(%superq(_sort)));

    /* Get runtime variable metadata in specification order */
    proc sql;
        create table work._bc_vars as
        select *
        from &_varmeta
        where upcase(strip(DATASET))="&_dsn"
        order by ORDER;
    quit;

    %let _nvars=0;
    %let _keep=;

    proc sql noprint;
        select count(*) into :_nvars trimmed
        from work._bc_vars;

        select strip(VARIABLE) into :_keep separated by " "
        from work._bc_vars;
    quit;

    %if &_nvars=0 %then %do;
        %put ERROR: BUILD_CDISC: No variable metadata found for &_dsn in &_varmeta..;
        %return;
    %end;

    /* Identify variables required by metadata but absent from the input */
    %let _missing=;
    %let _dsid=%sysfunc(open(&inds,i));

    %if &_dsid %then %do;
        %do _i=1 %to %sysfunc(countw(%superq(_keep),%str( )));
            %let _var=%scan(%superq(_keep),&_i,%str( ));
            %if %sysfunc(varnum(&_dsid,&_var))=0 %then %let _missing=&_missing &_var;
        %end;
        %let _rc=%sysfunc(close(&_dsid));
    %end;

    %let _missing=%sysfunc(compbl(%superq(_missing)));

    %if %length(%superq(_missing)) %then
        %put WARNING: BUILD_CDISC: Variables in SPEC but not present in &inds: &_missing..;

    /* Identify the SDTM sequence variable when one is defined */
    %let _seqvar=;
    %let _seqcnt=0;

    %if &_dev=SDTM %then %do;
        proc sql noprint;
            select count(*) into :_seqcnt trimmed
            from work._bc_vars
            where upcase(strip(VARIABLE)) like '%SEQ';

            select strip(VARIABLE) into :_seqvar trimmed
            from work._bc_vars
            where upcase(strip(VARIABLE)) like '%SEQ';
        quit;

        %if &_seqcnt > 1 %then %do;
            %put ERROR: BUILD_CDISC: More than one --SEQ variable was found for &_dsn..;
            %return;
        %end;
    %end;

    /* Exclude --SEQ from the pre-sequence sort */
    %let _sort_no_seq=&_sort;

    %if %length(%superq(_seqvar)) %then %do;
        %let _sort_no_seq=%sysfunc(prxchange(s/\b&_seqvar\b//i,-1,%superq(_sort_no_seq)));
        %let _sort_no_seq=%sysfunc(compbl(%superq(_sort_no_seq)));
    %end;

    /* Sort the programmed dataset before sequence generation */
    %if %length(%superq(_sort_no_seq)) %then %do;
        proc sort data=&inds out=work._bc_main;
            by &_sort_no_seq;
        run;
    %end;
    %else %do;
        data work._bc_main;
            set &inds;
        run;
    %end;

    /* Generate SDTM --SEQ within subject when applicable */
    %if &_dev=SDTM and %length(%superq(_seqvar)) %then %do;
        %let _seqby=;
        %let _dsid=%sysfunc(open(work._bc_main,i));

        %if &_dsid %then %do;
            %if %sysfunc(varnum(&_dsid,STUDYID)) > 0 %then %let _seqby=STUDYID;
            %if %sysfunc(varnum(&_dsid,USUBJID)) > 0 %then %let _seqby=&_seqby USUBJID;
            %let _rc=%sysfunc(close(&_dsid));
        %end;

        %let _seqby=%sysfunc(compbl(%superq(_seqby)));

        %if %length(%superq(_seqby)) %then %do;
            proc sort data=work._bc_main;
                by &_seqby &_sort_no_seq;
            run;

            data work._bc_main;
                set work._bc_main;
                by &_seqby &_sort_no_seq;
                retain &_seqvar;
                if first.%scan(&_seqby,-1,%str( )) then &_seqvar=1;
                else &_seqvar+1;
            run;
        %end;
        %else %do;
            data work._bc_main;
                set work._bc_main;
                &_seqvar=_N_;
            run;
        %end;
    %end;

    /* Build one ATTRIB statement for variable labels */
    %let _attr=;

    data _null_;
        set work._bc_vars end=eof;
        length _piece _all $32767;
        retain _all;

        if not missing(LABEL) then do;
            _piece=catx(' ',strip(VARIABLE),cats('label=',quote(trim(LABEL))));
            _all=catx(' ',_all,_piece);
        end;

        if eof then call symputx('_attr',_all,'L');
    run;

    /* Remove an existing target so success reflects this execution */
    proc datasets library=&_outlib nolist;
        delete &_dsn;
    quit;

    /* Create final dataset in specification variable order */
    data &_outlib..&_dsn;
        %if %length(%superq(_attr)) %then %do;
            attrib &_attr;
        %end;
        retain &_keep;
        set work._bc_main;
        keep &_keep;
    run;

    /* Apply final dataset sort order */
    %if %sysfunc(exist(&_outlib..&_dsn)) and %length(%superq(_sort)) %then %do;
        proc sort data=&_outlib..&_dsn;
            by &_sort;
        run;
    %end;

    /* Create SUPPxx for SDTM when supplemental variables are defined */
    %let _suppcnt=0;
    %let _suppobs=0;

    %if &_dev=SDTM and %sysfunc(exist(&_suppmeta)) %then %do;
        proc sql noprint;
            select count(*) into :_suppcnt trimmed
            from &_suppmeta
            where upcase(strip(DATASET))="&_dsn";
        quit;

        %if &_suppcnt > 0 %then %do;
            /* Determine whether optional SUPP metadata columns are available */
            %let _has_eval=0;
            %let _has_idvar=0;
            %let _dsid=%sysfunc(open(&_suppmeta,i));

            %if &_dsid %then %do;
                %if %sysfunc(varnum(&_dsid,EVALUATOR)) > 0 %then %let _has_eval=1;
                %if %sysfunc(varnum(&_dsid,IDVAR)) > 0 %then %let _has_idvar=1;
                %let _rc=%sysfunc(close(&_dsid));
            %end;

            /* Build each supplemental qualifier directly from WORK._BC_MAIN. */
            proc sql;
                create table work._bc_supp as
                select STUDYID, USUBJID,
                       "" as RDOMAIN length=8,
                       "" as IDVAR length=32,
                       "" as IDVARVAL length=200,
                       "" as QNAM length=8,
                       "" as QLABEL length=40,
                       "" as QVAL length=200,
                       "" as QORIG length=20,
                       "" as QEVAL length=40
                from work._bc_main
                where 0;
            quit;

            data _null_;
                set &_suppmeta;
                where upcase(strip(DATASET))="&_dsn";
                length _code $32767 _source _eval _idvar $200;

                _source=cats('_',strip(VARIABLE));
                _eval='';
                _idvar='';

                %if &_has_eval %then %do;
                    _eval=strip(vvaluex('EVALUATOR'));
                %end;

                %if &_has_idvar %then %do;
                    _idvar=strip(vvaluex('IDVAR'));
                %end;

                _code=catx(' ',
                    'data work._bc_one_supp;',
                    'set work._bc_main;',
                    'length RDOMAIN $8 IDVAR $32 IDVARVAL $200 QNAM $8 QLABEL $40 QVAL $200 QORIG $20 QEVAL $40;',
                    cats('RDOMAIN=',quote(trim(DATASET)),';'),
                    cats('QNAM=',quote(trim(VARIABLE)),';'),
                    cats('QLABEL=',quote(trim(LABEL)),';'),
                    cats('QVAL=strip(vvaluex(',quote(trim(_source)),'));'),
                    cats('QORIG=',quote(trim(ORIGIN)),';')
                );

                if not missing(_eval) then
                    _code=catx(' ',_code,cats('QEVAL=',quote(trim(_eval)),';'));
                else
                    _code=catx(' ',_code,'QEVAL="";');

                if not missing(_idvar) then do;
                    _code=catx(' ',_code,cats('IDVAR=',quote(trim(_idvar)),';'));
                    _code=catx(' ',_code,cats('IDVARVAL=strip(vvaluex(',quote(trim(_idvar)),'));'));
                end;
                else do;
                    _code=catx(' ',_code,'IDVAR="";');
                    _code=catx(' ',_code,'IDVARVAL="";');
                end;

                _code=catx(' ',_code,
                    'if not missing(QVAL);',
                    'keep STUDYID RDOMAIN USUBJID IDVAR IDVARVAL QNAM QLABEL QVAL QORIG QEVAL;',
                    'run;',
                    'proc append base=work._bc_supp data=work._bc_one_supp force;',
                    'run;'
                );

                call execute(_code);
            run;

            %if %sysfunc(exist(work._bc_supp)) %then %do;
                proc sql noprint;
                    select count(*) into :_suppobs trimmed
                    from work._bc_supp;
                quit;
            %end;

            %if &_suppobs > 0 %then %do;
                proc datasets library=&_outlib nolist;
                    delete SUPP&_dsn;
                quit;

                data &_outlib..SUPP&_dsn;
                    set work._bc_supp;
                run;

                proc sort data=&_outlib..SUPP&_dsn;
                    by STUDYID RDOMAIN USUBJID IDVAR IDVARVAL QNAM;
                run;
            %end;
            %else %do;
                %put NOTE: BUILD_CDISC: No nonmissing supplemental values found for &_dsn. SUPP&_dsn was not created.;
            %end;
        %end;
    %end;

    %if &_debug=Y %then %do;
        %put NOTE: BUILD_CDISC DEBUG: DEV=&_dev INDS=&inds DSN=&_dsn.;
        %put NOTE: BUILD_CDISC DEBUG: VARIABLES=&_nvars SORT=&_sort SEQ=&_seqvar.;
        %put NOTE: BUILD_CDISC DEBUG: SUPP METADATA=&_suppcnt SUPP OBSERVATIONS=&_suppobs.;
        %if %length(%superq(_missing)) %then
            %put NOTE: BUILD_CDISC DEBUG: MISSING INPUT VARIABLES=&_missing.;
        %put NOTE: BUILD_CDISC DEBUG: Temporary WORK._BC_* datasets retained.;
    %end;
    %else %do;
        proc datasets library=WORK nolist;
            delete _bc_vars _bc_main _bc_supp _bc_one_supp;
        quit;
    %end;

    %if %sysfunc(exist(&_outlib..&_dsn)) %then
        %put NOTE: BUILD_CDISC: &_outlib..&_dsn successfully created.;
    %else
        %put ERROR: BUILD_CDISC: &_outlib..&_dsn was not created.;

    %if &_dev=SDTM and &_suppobs > 0 %then %do;
        %if %sysfunc(exist(&_outlib..SUPP&_dsn)) %then
            %put NOTE: BUILD_CDISC: &_outlib..SUPP&_dsn successfully created.;
        %else
            %put ERROR: BUILD_CDISC: &_outlib..SUPP&_dsn was not created.;
    %end;

%mend build_cdisc;